spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avito
    username: postgres
    password: 7142218Sss
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: true

